const LevelData = {
  chapters: [
    {
      id: "chapter1",
      title: "The House",
      levels: [
        {
          id: 1,
          room: "The Kitchen Counter",
          roomDescription: "A sandwich sits on a plate. Crumbs scatter the counter. A knife rests nearby.",
          cards: [
            { id: "L1C1", text: "Bread was placed on the plate" },
            { id: "L1C2", text: "Ingredients were laid out" },
            { id: "L1C3", text: "Knife was used to cut" },
            { id: "L1C4", text: "Sandwich was made" },
          ],
          correctSequence: ["L1C1", "L1C2", "L1C3", "L1C4"],
          act: 1,
        },
        {
          id: 2,
          room: "The Child's Bedroom",
          roomDescription: "A backpack sits by the door. Shoes are on. An empty cereal bowl rests on the desk.",
          cards: [
            { id: "L2C1", text: "Alarm went off" },
            { id: "L2C2", text: "Cereal eaten" },
            { id: "L2C3", text: "Shoes put on" },
            { id: "L2C4", text: "Backpack packed" },
          ],
          correctSequence: ["L2C1", "L2C2", "L2C3", "L2C4"],
          act: 1,
        },
        {
          id: 3,
          room: "The Living Room",
          roomDescription: "A movie case lies open. Two blankets are bunched on the couch. A popcorn bowl is empty.",
          cards: [
            { id: "L3C1", text: "Blankets brought out" },
            { id: "L3C2", text: "Popcorn made" },
            { id: "L3C3", text: "Movie started" },
            { id: "L3C4", text: "Fell asleep on couch" },
          ],
          correctSequence: ["L3C1", "L3C2", "L3C3", "L3C4"],
          act: 1,
        },
        {
          id: 4,
          room: "The Kitchen (Evening)",
          roomDescription: "Dirty dishes sit in the sink. A pot rests on the stove. A recipe book lies open.",
          cards: [
            { id: "L4C1", text: "Recipe selected" },
            { id: "L4C2", text: "Ingredients prepared" },
            { id: "L4C3", text: "Meal cooked" },
            { id: "L4C4", text: "Dishes left in sink" },
          ],
          correctSequence: ["L4C1", "L4C2", "L4C3", "L4C4"],
          act: 1,
        },
        {
          id: 5,
          room: "The Garden",
          roomDescription: "A watering can sits empty. Three plants are freshly watered. Muddy gloves rest on the step.",
          cards: [
            { id: "L5C1", text: "Gloves put on" },
            { id: "L5C2", text: "Watering can filled" },
            { id: "L5C3", text: "Plants watered" },
            { id: "L5C4", text: "Gloves left on step" },
          ],
          correctSequence: ["L5C1", "L5C2", "L5C3", "L5C4"],
          act: 1,
        },
        {
          id: 6,
          room: "The Child's Bedroom (Evening)",
          roomDescription: "A drawing sits half finished on the desk. Crayons are scattered. The lamp is on.",
          cards: [
            { id: "L6C1", text: "Lamp switched on" },
            { id: "L6C2", text: "Crayons taken out" },
            { id: "L6C3", text: "Drawing started" },
            { id: "L6C4", text: "Left unfinished" },
          ],
          correctSequence: ["L6C1", "L6C2", "L6C3", "L6C4"],
          act: 1,
        },
        {
          id: 7,
          room: "The Bathroom",
          roomDescription: "A wet towel lies on the floor. The toothbrush has been used. The mirror is slightly steamed.",
          cards: [
            { id: "L7C1", text: "Shower turned on" },
            { id: "L7C2", text: "Shower taken" },
            { id: "L7C3", text: "Mirror steamed" },
            { id: "L7C4", text: "Towel left on floor" },
          ],
          correctSequence: ["L7C1", "L7C2", "L7C3", "L7C4"],
          act: 1,
        },
        {
          id: 8,
          room: "The Front Door",
          roomDescription: "A coat hangs on the hook. Keys sit on the table. An umbrella stands wet and open.",
          cards: [
            { id: "L8C1", text: "Left the house" },
            { id: "L8C2", text: "Rain started" },
            { id: "L8C3", text: "Umbrella used" },
            { id: "L8C4", text: "Returned home" },
          ],
          correctSequence: ["L8C1", "L8C2", "L8C3", "L8C4"],
          act: 1,
        },
        {
          id: 9,
          room: "The Kitchen (Birthday)",
          roomDescription: "A cake sits on the counter. Candles are burned down. The icing bowl is empty.",
          cards: [
            { id: "L9C1", text: "Cake baked" },
            { id: "L9C2", text: "Icing prepared" },
            { id: "L9C3", text: "Candles placed" },
            { id: "L9C4", text: "Candles blown out" },
          ],
          correctSequence: ["L9C1", "L9C2", "L9C3", "L9C4"],
          act: 1,
        },
        {
          id: 10,
          room: "The Living Room (Evening)",
          roomDescription: "A wine glass sits half empty on one side of the couch. A blanket covers the other side. The TV is off.",
          cards: [
            { id: "L10C1", text: "TV turned on" },
            { id: "L10C2", text: "Wine poured" },
            { id: "L10C3", text: "Show watched" },
            { id: "L10C4", text: "One person fell asleep early" },
          ],
          correctSequence: ["L10C1", "L10C2", "L10C3", "L10C4"],
          act: 1,
        },
        {
          id: 11,
          room: "The Spare Room",
          roomDescription: "A suitcase lies open on the bed. Some clothes are folded inside. A pillow from the master bedroom sits at the edge.",
          cards: [
            { id: "L11C1", text: "Argument happened" },
            { id: "L11C2", text: "Suitcase brought out" },
            { id: "L11C3", text: "Clothes packed partially" },
            { id: "L11C4", text: "Pillow taken from bedroom" },
          ],
          correctSequence: ["L11C1", "L11C2", "L11C3", "L11C4"],
          act: 2,
        },
        {
          id: 12,
          room: "The Kitchen (Morning)",
          roomDescription: "One coffee cup sits on the table. One cup remains in the cupboard. A single plate has been used.",
          cards: [
            { id: "L12C1", text: "Woke up alone" },
            { id: "L12C2", text: "Coffee made for one" },
            { id: "L12C3", text: "Breakfast eaten alone" },
            { id: "L12C4", text: "Second cup left untouched" },
          ],
          correctSequence: ["L12C1", "L12C2", "L12C3", "L12C4"],
          act: 2,
        },
        {
          id: 13,
          room: "The Child's Bedroom (Morning)",
          roomDescription: "A backpack sits by the wrong door. Shoes are on the wrong feet. A bowl of cereal sits uneaten.",
          cards: [
            { id: "L13C1", text: "Woke up confused" },
            { id: "L13C2", text: "Shoes put on wrong" },
            { id: "L13C3", text: "Cereal poured" },
            { id: "L13C4", text: "Left without eating" },
          ],
          correctSequence: ["L13C1", "L13C2", "L13C3", "L13C4"],
          act: 2,
        },
        {
          id: 14,
          room: "The Living Room (Night)",
          roomDescription: "Two blankets sit on opposite ends of the couch. The TV is on. The lights are off.",
          cards: [
            { id: "L14C1", text: "Lights turned off" },
            { id: "L14C2", text: "TV left on" },
            { id: "L14C3", text: "Blankets taken to separate ends" },
            { id: "L14C4", text: "Silence settled" },
          ],
          correctSequence: ["L14C1", "L14C2", "L14C3", "L14C4"],
          act: 2,
        },
        {
          id: 15,
          room: "The Home Office",
          roomDescription: "A laptop sits open. A rectangle of light shows emails on the screen. The door is closed.",
          cards: [
            { id: "L15C1", text: "Door closed" },
            { id: "L15C2", text: "Laptop opened" },
            { id: "L15C3", text: "Emails read" },
            { id: "L15C4", text: "Door stayed closed" },
          ],
          correctSequence: ["L15C1", "L15C2", "L15C3", "L15C4"],
          act: 2,
        },
        {
          id: 16,
          room: "The Child's Bedroom (After School)",
          roomDescription: "A drawing lies torn in half on the floor. Crayons are put away. The curtains are drawn.",
          cards: [
            { id: "L16C1", text: "Came home from school" },
            { id: "L16C2", text: "Heard arguing" },
            { id: "L16C3", text: "Drawing torn" },
            { id: "L16C4", text: "Curtains closed" },
          ],
          correctSequence: ["L16C1", "L16C2", "L16C3", "L16C4"],
          act: 2,
        },
        {
          id: 17,
          room: "The Kitchen (Dinner)",
          roomDescription: "Three plates are set but one is untouched. The food is cold. A chair is pushed back hard.",
          cards: [
            { id: "L17C1", text: "Dinner prepared for three" },
            { id: "L17C2", text: "Table set" },
            { id: "L17C3", text: "Argument resumed" },
            { id: "L17C4", text: "One person left the table" },
          ],
          correctSequence: ["L17C1", "L17C2", "L17C3", "L17C4"],
          act: 2,
        },
        {
          id: 18,
          room: "The Front Door (Late Night)",
          roomDescription: "Keys are gone from the hook. A coat is missing. A note sits on the table.",
          cards: [
            { id: "L18C1", text: "Argument escalated" },
            { id: "L18C2", text: "Note written" },
            { id: "L18C3", text: "Coat taken" },
            { id: "L18C4", text: "Keys taken and door closed" },
          ],
          correctSequence: ["L18C1", "L18C2", "L18C3", "L18C4"],
          act: 2,
        },
        {
          id: 19,
          room: "The Spare Room (Now a Bedroom)",
          roomDescription: "The suitcase is unpacked. Clothes hang in the spare wardrobe. A book sits on the nightstand.",
          cards: [
            { id: "L19C1", text: "Decision made to stay separately" },
            { id: "L19C2", text: "Suitcase unpacked" },
            { id: "L19C3", text: "Wardrobe used" },
            { id: "L19C4", text: "Book brought for comfort" },
          ],
          correctSequence: ["L19C1", "L19C2", "L19C3", "L19C4"],
          act: 2,
        },
        {
          id: 20,
          room: "The Child's Bedroom (Night)",
          roomDescription: "A drawing on the desk shows two figures on opposite sides of a line with a smaller figure in the middle. The lamp is off. The door is open slightly.",
          cards: [
            { id: "L20C1", text: "Couldn't sleep" },
            { id: "L20C2", text: "Door opened slightly" },
            { id: "L20C3", text: "Drawing made in the dark" },
            { id: "L20C4", text: "Lamp left off" },
          ],
          correctSequence: ["L20C1", "L20C2", "L20C3", "L20C4"],
          act: 2,
        },
        {
          id: 21,
          room: "The Kitchen (Saturday Morning)",
          roomDescription: "Two coffee cups sit on the table. Both have been used. A newspaper lies between them.",
          cards: [
            { id: "L21C1", text: "Both woke up early" },
            { id: "L21C2", text: "Coffee made for two" },
            { id: "L21C3", text: "Newspaper shared" },
            { id: "L21C4", text: "Silence but together" },
          ],
          correctSequence: ["L21C1", "L21C2", "L21C3", "L21C4"],
          act: 3,
        },
        {
          id: 22,
          room: "The Garden (Spring)",
          roomDescription: "A new plant sits in a pot. Soil dusts the table. Two pairs of muddy gloves lie side by side.",
          cards: [
            { id: "L22C1", text: "Plant purchased" },
            { id: "L22C2", text: "Soil prepared" },
            { id: "L22C3", text: "Plant potted together" },
            { id: "L22C4", text: "Gloves left side by side" },
          ],
          correctSequence: ["L22C1", "L22C2", "L22C3", "L22C4"],
          act: 3,
        },
        {
          id: 23,
          room: "The Living Room",
          roomDescription: "One blanket sits on the couch. One wine glass is poured. A second glass is mid-journey from the kitchen.",
          cards: [
            { id: "L23C1", text: "One person sat down" },
            { id: "L23C2", text: "Other person decided to join" },
            { id: "L23C3", text: "Wine poured for two" },
            { id: "L23C4", text: "Blanket shared" },
          ],
          correctSequence: ["L23C1", "L23C2", "L23C3", "L23C4"],
          act: 3,
        },
        {
          id: 24,
          room: "The Home Office",
          roomDescription: "The laptop is closed. The door is open. A family photo sits on the desk that was not there before.",
          cards: [
            { id: "L24C1", text: "Photo found in drawer" },
            { id: "L24C2", text: "Door opened" },
            { id: "L24C3", text: "Laptop closed" },
            { id: "L24C4", text: "Photo placed on desk" },
          ],
          correctSequence: ["L24C1", "L24C2", "L24C3", "L24C4"],
          act: 3,
        },
        {
          id: 25,
          room: "The Child's Bedroom (After School)",
          roomDescription: "A new drawing sits on the desk showing three figures with no line between them. Crayons are scattered everywhere.",
          cards: [
            { id: "L25C1", text: "Came home from school" },
            { id: "L25C2", text: "Good news shared" },
            { id: "L25C3", text: "Crayons taken out" },
            { id: "L25C4", text: "New drawing made" },
          ],
          correctSequence: ["L25C1", "L25C2", "L25C3", "L25C4"],
          act: 3,
        },
        {
          id: 26,
          room: "The Kitchen (Cooking Together)",
          roomDescription: "Two aprons hang on hooks. Multiple pots have been used. A mess covers every surface. A finished meal sits on the table.",
          cards: [
            { id: "L26C1", text: "Recipe chosen together" },
            { id: "L26C2", text: "Cooking started" },
            { id: "L26C3", text: "Mess made" },
            { id: "L26C4", text: "Meal finished and laughed about" },
          ],
          correctSequence: ["L26C1", "L26C2", "L26C3", "L26C4"],
          act: 3,
        },
        {
          id: 27,
          room: "The Spare Room (Becoming Something Else)",
          roomDescription: "The suitcase is gone. The bed is stripped. A desk sits half moved in. Art supplies cover the floor.",
          cards: [
            { id: "L27C1", text: "Decision made to reclaim the room" },
            { id: "L27C2", text: "Suitcase removed" },
            { id: "L27C3", text: "Bed stripped" },
            { id: "L27C4", text: "Desk moved in for the child" },
          ],
          correctSequence: ["L27C1", "L27C2", "L27C3", "L27C4"],
          act: 3,
        },
        {
          id: 28,
          room: "The Front Door (Evening)",
          roomDescription: "Three coats hang on the hook. Three pairs of shoes sit by the door. A restaurant receipt lies on the table.",
          cards: [
            { id: "L28C1", text: "Reservation made" },
            { id: "L28C2", text: "All three left together" },
            { id: "L28C3", text: "Dinner out as a family" },
            { id: "L28C4", text: "Came home together" },
          ],
          correctSequence: ["L28C1", "L28C2", "L28C3", "L28C4"],
          act: 3,
        },
        {
          id: 29,
          room: "The Child's Bedroom (Bedtime)",
          roomDescription: "Two pairs of adult shoes sit outside the door. A book lies open on the bed. The lamp glows on low.",
          cards: [
            { id: "L29C1", text: "Bedtime started" },
            { id: "L29C2", text: "Story requested" },
            { id: "L29C3", text: "Both parents read together" },
            { id: "L29C4", text: "Child fell asleep" },
          ],
          correctSequence: ["L29C1", "L29C2", "L29C3", "L29C4"],
          act: 3,
        },
        {
          id: 30,
          room: "The Living Room (Final)",
          roomDescription: "Two wine glasses sit full and untouched. A child's drawing hangs framed on the wall. One blanket covers the couch. The TV is off. A plant rests by the window.",
          cards: [
            { id: "L30C1", text: "Evening settled" },
            { id: "L30C2", text: "Wine poured" },
            { id: "L30C3", text: "Drawing noticed and appreciated" },
            { id: "L30C4", text: "Sat together in the quiet" },
          ],
          correctSequence: ["L30C1", "L30C2", "L30C3", "L30C4"],
          act: 3,
        },
      ],
    },
  ],
};